const mongoose = require('mongoose');

const analyticsSchema = new mongoose.Schema({
  date: String,
  outTime: String ,
  inTime: String ,
  vehicleId: String,
  vehicle: String,
  vehicleNo: String,
  testNo: Number,
  driver: String,
  weight: Number,
  maxSpeed: Number,
  avgSpeed: Number,
  initDistance: Number,
  finalDistance: Number,
  avgRpm: Number,
  ambTemperature: Number,
  drivingMode: Number,
  initMotorTemperature: Number,
  finalMotorTemperature: Number,
  avgMotorTemperature: Number,
  maxMotorTemperature: Number,
  initControllerTemperature: Number,
  finalControllerTemperature: Number,
  avgControllerTemperature: Number,
  maxControllerTemperature: Number,
  initVoltage: Number,
  finalVoltage: Number,
  maxCurrent: Number,
  avgCurrent: Number,
  initSOC: Number,
  finalSOC: Number,
  initAh: Number,
  finalAH: Number,
  whrConsumed: Number,
  maxMosTemperature: Number,
  maxBalanceTemperature: Number,
  batteryFault: Number,
  highCellVoltage: Number,
  lowCellVoltage: Number,
  maxCellDifference: Number,
  initCellDifference: Number,
  efficiency: Number,
  avgGradient: Number,
  maxGradient: Number,
  avgWhkm: Number,
  maxWhkm: Number,
  chargingStartTime: String,
  chargingEndTime: String,
  chargingStartSoc: Number,
  chargingEndSoc: Number,
  chargingCurrent: Number,
  batteryHealthCharging: String,
  batteryEfficiency: Number,
  chargingRemark: String,
  CurrentDate: {
    type: Date,
    default: () => new Date().toISOString().slice(0, 10)
  },
});

const Analytics = mongoose.model('Analytics', analyticsSchema);
module.exports = Analytics;
